name: Renovate

on: issues

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: docker run --rm renovate/renovate --token ${TOKEN} ${GITHUB_REPOSITORY}
        env:
          TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
