name: Renovate

on: issues

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://renovate/renovate:slim
        with:
          args: --token ${{secrets.PERSONAL_ACCESS_TOKEN}} ${{github.repository}}
