name: Renovate

on: issues

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: docker run --rm renovate/renovate --token ${GITHUB_TOKEN} ${GITHUB_REPOSITORY}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
