name: Renovate

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://renovate/renovate:slim
        with:
          args: --token ${{secrets.PERSONAL_ACCESS_TOKEN}} ${{github.repository}}
