name: Renovate

on: issues

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: renovate/renovate:latest
        with:
          args: "--token ${{secrets.PERSONAL_ACCESS_TOKEN}} ${GITHUB_REPOSITORY}"
